import type { Wilaya, Commune, DeliveryMethod, DeliveryOption } from './types';

export const wilayas: Wilaya[] = [
  {
    id: 1,
    name: 'Adrar',
    nameAr: 'أدرار',
    deliveryPrices: { bureau: 800, domicile: 1200 },
    requiresCommune: false,
    communes: [],
  },
  {
    id: 2,
    name: 'Chlef',
    nameAr: 'الشلف',
    deliveryPrices: { bureau: 600, domicile: 1000 },
    requiresCommune: true,
    communes: [
      { id: 1, name: 'Chlef', nameAr: 'الشلف', wilayaId: 2 },
      { id: 2, name: 'Ténès', nameAr: 'تنس', wilayaId: 2 },
      { id: 3, name: 'El Karimia', nameAr: 'الكرمية', wilayaId: 2 },
      { id: 4, name: 'Oued Fodda', nameAr: 'وادي الفضة', wilayaId: 2 },
    ],
  },
  {
    id: 3,
    name: 'Laghouat',
    nameAr: 'الأغواط',
    deliveryPrices: { bureau: 700, domicile: 1100 },
    requiresCommune: false,
    communes: [],
  },
  {
    id: 4,
    name: 'Oum El Bouaghi',
    nameAr: 'أم البواقي',
    deliveryPrices: { bureau: 650, domicile: 1050 },
    requiresCommune: false,
    communes: [],
  },
  {
    id: 5,
    name: 'Batna',
    nameAr: 'باتنة',
    deliveryPrices: { bureau: 600, domicile: 1000 },
    requiresCommune: true,
    communes: [
      { id: 5, name: 'Batna', nameAr: 'باتنة', wilayaId: 5 },
      { id: 6, name: 'Barika', nameAr: 'بريكة', wilayaId: 5 },
      { id: 7, name: 'Merouana', nameAr: 'مروانة', wilayaId: 5 },
      { id: 8, name: 'N\'Gaous', nameAr: 'نڨاوس', wilayaId: 5 },
    ],
  },
  {
    id: 6,
    name: 'Béjaïa',
    nameAr: 'بجاية',
    deliveryPrices: { bureau: 550, domicile: 900 },
    requiresCommune: true,
    communes: [
      { id: 9, name: 'Béjaïa', nameAr: 'بجاية', wilayaId: 6 },
      { id: 10, name: 'Akbou', nameAr: 'أقبو', wilayaId: 6 },
      { id: 11, name: 'Seddouk', nameAr: 'صندوق', wilayaId: 6 },
      { id: 12, name: 'Timezrit', nameAr: 'تمزرت', wilayaId: 6 },
    ],
  },
  {
    id: 7,
    name: 'Biskra',
    nameAr: 'بسكرة',
    deliveryPrices: { bureau: 700, domicile: 1100 },
    requiresCommune: false,
    communes: [],
  },
  {
    id: 8,
    name: 'Béchar',
    nameAr: 'بشار',
    deliveryPrices: { bureau: 900, domicile: 1300 },
    requiresCommune: false,
    communes: [],
  },
  {
    id: 9,
    name: 'Blida',
    nameAr: 'البليدة',
    deliveryPrices: { bureau: 400, domicile: 700 },
    requiresCommune: true,
    communes: [
      { id: 13, name: 'Blida', nameAr: 'البليدة', wilayaId: 9 },
      { id: 14, name: 'Boufarik', nameAr: 'بوفاريك', wilayaId: 9 },
      { id: 15, name: 'Bougara', nameAr: 'بوقرة', wilayaId: 9 },
      { id: 16, name: 'Mouzaïa', nameAr: 'مزايا', wilayaId: 9 },
    ],
  },
  {
    id: 10,
    name: 'Bouira',
    nameAr: 'البويرة',
    deliveryPrices: { bureau: 500, domicile: 850 },
    requiresCommune: false,
    communes: [],
  },
  {
    id: 11,
    name: 'Tamanrasset',
    nameAr: 'تمنراست',
    deliveryPrices: { bureau: 1200, domicile: 1600 },
    requiresCommune: false,
    communes: [],
  },
  {
    id: 12,
    name: 'Tébessa',
    nameAr: 'تبسة',
    deliveryPrices: { bureau: 750, domicile: 1150 },
    requiresCommune: false,
    communes: [],
  },
  {
    id: 13,
    name: 'Tlemcen',
    nameAr: 'تلمسان',
    deliveryPrices: { bureau: 650, domicile: 1050 },
    requiresCommune: true,
    communes: [
      { id: 17, name: 'Tlemcen', nameAr: 'تلمسان', wilayaId: 13 },
      { id: 18, name: 'Maghnia', nameAr: 'مغنية', wilayaId: 13 },
      { id: 19, name: 'Hennaya', nameAr: 'هناية', wilayaId: 13 },
      { id: 20, name: 'Chetouane', nameAr: 'شتوان', wilayaId: 13 },
    ],
  },
  {
    id: 14,
    name: 'Tiaret',
    nameAr: 'تيارت',
    deliveryPrices: { bureau: 650, domicile: 1050 },
    requiresCommune: false,
    communes: [],
  },
  {
    id: 15,
    name: 'Tizi Ouzou',
    nameAr: 'تيزي وزو',
    deliveryPrices: { bureau: 500, domicile: 850 },
    requiresCommune: true,
    communes: [
      { id: 21, name: 'Tizi Ouzou', nameAr: 'تيزي وزو', wilayaId: 15 },
      { id: 22, name: 'Draâ Ben Khedda', nameAr: 'ذراع بن خدة', wilayaId: 15 },
      { id: 23, name: 'Azazga', nameAr: 'آزازقة', wilayaId: 15 },
      { id: 24, name: 'Boghni', nameAr: 'بوغني', wilayaId: 15 },
    ],
  },
  {
    id: 16,
    name: 'Algiers (Alger)',
    nameAr: 'الجزائر',
    deliveryPrices: { bureau: 300, domicile: 500 },
    requiresCommune: true,
    communes: [
      { id: 25, name: 'Algiers Centre', nameAr: 'الجزائر الوسطى', wilayaId: 16 },
      { id: 26, name: 'Bab El Oued', nameAr: 'باب الواد', wilayaId: 16 },
      { id: 27, name: 'Bordj El Kiffan', nameAr: 'برج الكيفان', wilayaId: 16 },
      { id: 28, name: 'Birtouta', nameAr: 'بئر توتة', wilayaId: 16 },
      { id: 29, name: 'Casbah', nameAr: 'القصبة', wilayaId: 16 },
      { id: 30, name: 'Dar El Beïda', nameAr: 'دار البيضاء', wilayaId: 16 },
      { id: 31, name: 'Douéra', nameAr: 'الدويرة', wilayaId: 16 },
      { id: 32, name: 'El Harrach', nameAr: 'الحراش', wilayaId: 16 },
      { id: 33, name: 'Hussein Dey', nameAr: 'حسين داي', wilayaId: 16 },
      { id: 34, name: 'Hydra', nameAr: 'حيدرة', wilayaId: 16 },
      { id: 35, name: 'Kouba', nameAr: 'قبة', wilayaId: 16 },
      { id: 36, name: 'Les Eucalyptus', nameAr: 'الأوكاليبتوس', wilayaId: 16 },
      { id: 37, name: 'Oued Koriche', nameAr: 'وادي قريش', wilayaId: 16 },
      { id: 38, name: 'Sidi M\'Hamed', nameAr: 'سيدي أمحمد', wilayaId: 16 },
    ],
  },
  {
    id: 17,
    name: 'Djelfa',
    nameAr: 'الجلفة',
    deliveryPrices: { bureau: 750, domicile: 1150 },
    requiresCommune: false,
    communes: [],
  },
  {
    id: 18,
    name: 'Jijel',
    nameAr: 'جيجل',
    deliveryPrices: { bureau: 600, domicile: 1000 },
    requiresCommune: false,
    communes: [],
  },
  {
    id: 19,
    name: 'Sétif',
    nameAr: 'سطيف',
    deliveryPrices: { bureau: 600, domicile: 1000 },
    requiresCommune: true,
    communes: [
      { id: 39, name: 'Sétif', nameAr: 'سطيف', wilayaId: 19 },
      { id: 40, name: 'El Eulma', nameAr: 'العلمة', wilayaId: 19 },
      { id: 41, name: 'Aïn Oulmène', nameAr: 'عين اولمن', wilayaId: 19 },
      { id: 42, name: 'Aïn Arnat', nameAr: 'عين أرنات', wilayaId: 19 },
    ],
  },
  {
    id: 20,
    name: 'Saïda',
    nameAr: 'سعيدة',
    deliveryPrices: { bureau: 700, domicile: 1100 },
    requiresCommune: false,
    communes: [],
  },
  {
    id: 21,
    name: 'Skikda',
    nameAr: 'سكيكدة',
    deliveryPrices: { bureau: 600, domicile: 1000 },
    requiresCommune: false,
    communes: [],
  },
  {
    id: 22,
    name: 'Sidi Bel Abbès',
    nameAr: 'سيدي بلعباس',
    deliveryPrices: { bureau: 650, domicile: 1050 },
    requiresCommune: false,
    communes: [],
  },
  {
    id: 23,
    name: 'Annaba',
    nameAr: 'عنابة',
    deliveryPrices: { bureau: 550, domicile: 900 },
    requiresCommune: true,
    communes: [
      { id: 43, name: 'Annaba', nameAr: 'عنابة', wilayaId: 23 },
      { id: 44, name: 'El Hadjar', nameAr: 'الحجار', wilayaId: 23 },
      { id: 45, name: 'Sidi Amar', nameAr: 'سيدي عمار', wilayaId: 23 },
      { id: 46, name: 'Berrahal', nameAr: 'برحال', wilayaId: 23 },
    ],
  },
  {
    id: 24,
    name: 'Guelma',
    nameAr: 'قالمة',
    deliveryPrices: { bureau: 600, domicile: 1000 },
    requiresCommune: false,
    communes: [],
  },
  {
    id: 25,
    name: 'Constantine',
    nameAr: 'قسنطينة',
    deliveryPrices: { bureau: 550, domicile: 900 },
    requiresCommune: true,
    communes: [
      { id: 47, name: 'Constantine', nameAr: 'قسنطينة', wilayaId: 25 },
      { id: 48, name: 'El Khroub', nameAr: 'الخروب', wilayaId: 25 },
      { id: 49, name: 'Hamma Bouziane', nameAr: 'حامة بوزيان', wilayaId: 25 },
      { id: 50, name: 'Aïn Smara', nameAr: 'عين سمارة', wilayaId: 25 },
    ],
  },
  {
    id: 26,
    name: 'Médéa',
    nameAr: 'المدية',
    deliveryPrices: { bureau: 500, domicile: 850 },
    requiresCommune: false,
    communes: [],
  },
  {
    id: 27,
    name: 'Mostaganem',
    nameAr: 'مستغانم',
    deliveryPrices: { bureau: 600, domicile: 1000 },
    requiresCommune: false,
    communes: [],
  },
  {
    id: 28,
    name: 'M\'Sila',
    nameAr: 'المسيلة',
    deliveryPrices: { bureau: 650, domicile: 1050 },
    requiresCommune: false,
    communes: [],
  },
  {
    id: 29,
    name: 'Mascara',
    nameAr: 'معسكر',
    deliveryPrices: { bureau: 650, domicile: 1050 },
    requiresCommune: false,
    communes: [],
  },
  {
    id: 30,
    name: 'Ouargla',
    nameAr: 'ورقلة',
    deliveryPrices: { bureau: 850, domicile: 1250 },
    requiresCommune: false,
    communes: [],
  },
  {
    id: 31,
    name: 'Oran',
    nameAr: 'وهران',
    deliveryPrices: { bureau: 500, domicile: 850 },
    requiresCommune: true,
    communes: [
      { id: 51, name: 'Oran', nameAr: 'وهران', wilayaId: 31 },
      { id: 52, name: 'Aïn El Turk', nameAr: 'عين الترك', wilayaId: 31 },
      { id: 53, name: 'Es Sénia', nameAr: 'السانية', wilayaId: 31 },
      { id: 54, name: 'Bir El Djir', nameAr: 'بئر الجير', wilayaId: 31 },
    ],
  },
  {
    id: 32,
    name: 'El Bayadh',
    nameAr: 'البيض',
    deliveryPrices: { bureau: 800, domicile: 1200 },
    requiresCommune: false,
    communes: [],
  },
  {
    id: 33,
    name: 'Illizi',
    nameAr: 'إليزي',
    deliveryPrices: { bureau: 1100, domicile: 1500 },
    requiresCommune: false,
    communes: [],
  },
  {
    id: 34,
    name: 'Bordj Bou Arréridj',
    nameAr: 'برج بوعريريج',
    deliveryPrices: { bureau: 600, domicile: 1000 },
    requiresCommune: false,
    communes: [],
  },
  {
    id: 35,
    name: 'Boumerdès',
    nameAr: 'بومرداس',
    deliveryPrices: { bureau: 450, domicile: 750 },
    requiresCommune: true,
    communes: [
      { id: 55, name: 'Boumerdès', nameAr: 'بومرداس', wilayaId: 35 },
      { id: 56, name: 'Thénia', nameAr: 'الثنية', wilayaId: 35 },
      { id: 57, name: 'Khemis El Khechna', nameAr: 'خميس الخشنة', wilayaId: 35 },
      { id: 58, name: 'Dellys', nameAr: 'دلس', wilayaId: 35 },
    ],
  },
  {
    id: 36,
    name: 'El Tarf',
    nameAr: 'الطارف',
    deliveryPrices: { bureau: 600, domicile: 1000 },
    requiresCommune: false,
    communes: [],
  },
  {
    id: 37,
    name: 'Tindouf',
    nameAr: 'تندوف',
    deliveryPrices: { bureau: 1100, domicile: 1500 },
    requiresCommune: false,
    communes: [],
  },
  {
    id: 38,
    name: 'Tissemsilt',
    nameAr: 'تيسمسيلت',
    deliveryPrices: { bureau: 700, domicile: 1100 },
    requiresCommune: false,
    communes: [],
  },
  {
    id: 39,
    name: 'El Oued',
    nameAr: 'الوادي',
    deliveryPrices: { bureau: 850, domicile: 1250 },
    requiresCommune: false,
    communes: [],
  },
  {
    id: 40,
    name: 'Khenchela',
    nameAr: 'خنشلة',
    deliveryPrices: { bureau: 750, domicile: 1150 },
    requiresCommune: false,
    communes: [],
  },
  {
    id: 41,
    name: 'Souk Ahras',
    nameAr: 'سوق أهراس',
    deliveryPrices: { bureau: 650, domicile: 1050 },
    requiresCommune: false,
    communes: [],
  },
  {
    id: 42,
    name: 'Tipaza',
    nameAr: 'تيبازة',
    deliveryPrices: { bureau: 450, domicile: 750 },
    requiresCommune: true,
    communes: [
      { id: 59, name: 'Tipaza', nameAr: 'تيبازة', wilayaId: 42 },
      { id: 60, name: 'Cherchell', nameAr: 'شرشال', wilayaId: 42 },
      { id: 61, name: 'Gouraya', nameAr: 'غوراية', wilayaId: 42 },
      { id: 62, name: 'Menaceur', nameAr: 'مناصر', wilayaId: 42 },
    ],
  },
  {
    id: 43,
    name: 'Mila',
    nameAr: 'ميلة',
    deliveryPrices: { bureau: 600, domicile: 1000 },
    requiresCommune: false,
    communes: [],
  },
  {
    id: 44,
    name: 'Aïn Defla',
    nameAr: 'عين الدفلى',
    deliveryPrices: { bureau: 550, domicile: 900 },
    requiresCommune: false,
    communes: [],
  },
  {
    id: 45,
    name: 'Naâma',
    nameAr: 'النعامة',
    deliveryPrices: { bureau: 800, domicile: 1200 },
    requiresCommune: false,
    communes: [],
  },
  {
    id: 46,
    name: 'Aïn Témouchent',
    nameAr: 'عين تموشنت',
    deliveryPrices: { bureau: 650, domicile: 1050 },
    requiresCommune: false,
    communes: [],
  },
  {
    id: 47,
    name: 'Ghardaïa',
    nameAr: 'غرداية',
    deliveryPrices: { bureau: 800, domicile: 1200 },
    requiresCommune: false,
    communes: [],
  },
  {
    id: 48,
    name: 'Relizane',
    nameAr: 'غليزان',
    deliveryPrices: { bureau: 650, domicile: 1050 },
    requiresCommune: false,
    communes: [],
  },
  {
    id: 49,
    name: 'Timimoun',
    nameAr: 'تيميمون',
    deliveryPrices: { bureau: 900, domicile: 1300 },
    requiresCommune: false,
    communes: [],
  },
  {
    id: 50,
    name: 'Bordj Badji Mokhtar',
    nameAr: 'برج باجي مختار',
    deliveryPrices: { bureau: 1100, domicile: 1500 },
    requiresCommune: false,
    communes: [],
  },
  {
    id: 51,
    name: 'Ouled Djellal',
    nameAr: 'أولاد جلال',
    deliveryPrices: { bureau: 750, domicile: 1150 },
    requiresCommune: false,
    communes: [],
  },
  {
    id: 52,
    name: 'Béni Abbès',
    nameAr: 'بني عباس',
    deliveryPrices: { bureau: 950, domicile: 1350 },
    requiresCommune: false,
    communes: [],
  },
  {
    id: 53,
    name: 'In Salah',
    nameAr: 'عين صالح',
    deliveryPrices: { bureau: 1000, domicile: 1400 },
    requiresCommune: false,
    communes: [],
  },
  {
    id: 54,
    name: 'In Guezzam',
    nameAr: 'عين قزام',
    deliveryPrices: { bureau: 1100, domicile: 1500 },
    requiresCommune: false,
    communes: [],
  },
  {
    id: 55,
    name: 'Touggourt',
    nameAr: 'تقرت',
    deliveryPrices: { bureau: 850, domicile: 1250 },
    requiresCommune: false,
    communes: [],
  },
  {
    id: 56,
    name: 'Djanet',
    nameAr: 'جانت',
    deliveryPrices: { bureau: 1100, domicile: 1500 },
    requiresCommune: false,
    communes: [],
  },
  {
    id: 57,
    name: "El M'Ghair",
    nameAr: 'المغير',
    deliveryPrices: { bureau: 850, domicile: 1250 },
    requiresCommune: false,
    communes: [],
  },
  {
    id: 58,
    name: 'El Meniaa',
    nameAr: 'المنيعة',
    deliveryPrices: { bureau: 900, domicile: 1300 },
    requiresCommune: false,
    communes: [],
  },
];

export const deliveryMethods: Record<DeliveryMethod, { label: string; description: string; estimatedDays: string }> = {
  'yalidine-bureau': {
    label: 'Yalidine Bureau',
    description: 'Pick up at the nearest Yalidine office. Lower cost, you collect when ready.',
    estimatedDays: '2-4 business days',
  },
  'yalidine-domicile': {
    label: 'Yalidine Domicile',
    description: 'Delivered to your door. Higher cost, maximum convenience.',
    estimatedDays: '2-4 business days',
  },
};

export function getWilayaById(id: number): Wilaya | undefined {
  return wilayas.find((w) => w.id === id);
}

export function getCommunesByWilaya(wilayaId: number): Commune[] {
  const wilaya = getWilayaById(wilayaId);
  return wilaya?.communes ?? [];
}

export function getDeliveryOptions(wilayaId: number, communeId?: number): DeliveryOption[] {
  const wilaya = getWilayaById(wilayaId);
  if (!wilaya) return [];

  const options: DeliveryOption[] = [
    {
      method: 'yalidine-bureau',
      wilayaId,
      communeId,
      price: wilaya.deliveryPrices.bureau,
      estimatedDays: deliveryMethods['yalidine-bureau'].estimatedDays,
      label: deliveryMethods['yalidine-bureau'].label,
      description: deliveryMethods['yalidine-bureau'].description,
    },
    {
      method: 'yalidine-domicile',
      wilayaId,
      communeId,
      price: wilaya.deliveryPrices.domicile,
      estimatedDays: deliveryMethods['yalidine-domicile'].estimatedDays,
      label: deliveryMethods['yalidine-domicile'].label,
      description: deliveryMethods['yalidine-domicile'].description,
    },
  ];

  return options;
}

export function calculateDeliveryPrice(wilayaId: number, method: DeliveryMethod): number {
  const wilaya = getWilayaById(wilayaId);
  if (!wilaya) return 0;
  return wilaya.deliveryPrices[method === 'yalidine-bureau' ? 'bureau' : 'domicile'];
}